[theme]
base = "dark"
primaryColor = "#818cf8"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
